### ISSUE TITLE
TypeError: Can't instantiate abstract class Euclidean with abstract methods get_metric, score_pairs

### ISSUE THREAD

**Issue by Zeros12** [LcDog/DomainAdaptiveReID#6]
Hi, thank you for nice work. I am getting the following error when I run source_train.py.

Files already downloaded and verified
Market1501 dataset loaded
  subset   | # ids | # images
  ---------------------------
  train    |   676 |    11744
  val      |    75 |     1192
  trainval |   751 |    12936
  query    |   750 |     3368
  gallery  |   751 |    15913
Traceback (most recent call last):
  File "source_train.py", line 311, in <module>
    main(parser.parse_args())
  File "source_train.py", line 196, in main
    metric = DistanceMetric(algorithm=args.dist_metric)
  File "/home/DomainAdaptiveReID-master/reid/dist_metric.py", line 13, in __init__
    self.metric = get_metric(algorithm, *args, **kwargs)
  File "/home/DomainAdaptiveReID-master/reid/metric_learning/__init__.py", line 25, in get_metric
    return __factory[algorithm](*args, **kwargs)
TypeError: Can't instantiate abstract class Euclidean with abstract methods get_metric, score_pairs

**Comment by deep0learning** [comment]
I also got the same error.

**Comment by anilsh** [comment]
Any way to resolve the error?

**Comment by lsongx** [comment]
Hi, this reposity uses metric_learn 0.3.0. It this the same with your settings?

**Comment by HenryZhangJianhe** [comment]
I used 0.2.0,0.3.0, or 0.4.0 to run and got another error :ImportError: cannot import name 'graph_lasso'

And if I use 0.5.0, 0.6.0, I still got error same as title.

**Comment by HenryZhangJianhe** [comment]
I fixd it as follow step
scikit-learn 0.20.0
metric-learn 0.4.0
